### ISSUE TITLE
No Shorthand Name Exists for Los Angeles Rams or Los Angeles Chargers

### ISSUE THREAD

**Issue by n-devr** [bradforj287/NFLBoxScoreScraper#2]
### Expected behavior
Shorthand name exists for the new LA teams, allowing box score JSON files to be named properly.

### Actual behavior
Shorthand name doesn't exist for the new LA teams, adding `undefined` to box score file names.
e.g. 
> week_1_SFO_undefined.json

### Steps to reproduce this behavior
Scrape box scores for the 2016 or 2017 NFL seasons.

**Comment by n-devr** [comment]
I created a quick pull request to resolve this issue: #3 

Also wanted to say thanks for open-sourcing this project - I had set out to build almost exactly the same thing before I stumbled across your repo and it's worked without a hitch so far.  Your time and effort is much appreciated!

**Comment by bradforj287** [comment]
Thanks for submitting the fix. Glad you are finding the project useful.
